package org.mittman.generate.format;

import java.util.Properties;

/**
 * Formats objects generated by a Generator.
 * 
 * GeneratedObjectFormatter objects must implement
 * a no-arg constructor
 * 
 * @author Edward Mittman
 *
 */
public interface GeneratedObjectFormatter<T> {
	/**
	 * Initialize the object from a set of properties
	 * @param properties
	 */
	void initialize(Properties properties);
	
	/**
	 * A list of properties that can be
	 * specified for this formatter
	 * @return
	 */
	String []propertyNames();
	
	/**
	 * Format an object as a string
	 * @param o
	 * @return
	 */
	String format(T o);
}
